name: Checkmate

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
  issue_comment:

# cancel old edit events being processed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-checklists:
    name: Validate Checklists
    runs-on: ubuntu-24.04
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v3.0.0
        id: secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_RO }}
          #
          APP_ID: 'op://GitHub.Actions/GitHub/corva-bot/APP_ID'
          PRIVATE_KEY: 'op://GitHub.Actions/GitHub/corva-bot/PRIVATE_KEY'
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v2.1.4
        id: token
        with:
          app-id: ${{ steps.secrets.outputs.APP_ID }}
          private-key: ${{ steps.secrets.outputs.PRIVATE_KEY }}
      - name: Validate Checklists
        uses: roryq/checkmate@v1.0.5
        with:
          # TODO: when using non-standard token, action fails to properly discover previous comments and goes into infinite loop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            "**/*.md":
              - 'I have got the grammar police to proofread my changes.'
            "tools/**/*":
              - 'I am changing tools, not only apps.'
      - name: Add PR status check
        uses: ouzi-dev/commit-status-updater@v2.0.2
        if: ${{ (success() || failure()) && (github.event_name == 'pull_request' || github.event_name == 'push') }}
        with:
          token: ${{ steps.token.outputs.token }}
          name: 'Checkmate'
          status: ${{ job.status }}
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          description: ${{ job.status == 'success' && 'Checklist completed' || 'Incomplete Checklist. Check PR annotations' }}
