name: 'Semantic PR'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths-ignore:
      - .release-please-manifest.json
      - package-lock.json
      - apps/**/CHANGELOG.md
      - apps/**/package.json

jobs:
  validate-pr:
    # Required: GitHub repository using squash & merge strategy and option "Default to PR title for squash merge commits" is selected.
    name: Validate PR title
    uses: corva-ai/gh-actions/.github/workflows/workflow-semantic-pr.yml@develop
    secrets: inherit
